In [1]:
import pandas as pd
import numpy as np

In [2]:
sizes = [36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66]
colors = ['Black',"Brown"]

In [3]:
product = "Shoes"
cols = ['Product','Category','Brand','Type','Color','Size',
       ]
category = ['Ankle Shoe','Corporate shoe','Half Shoe',
            'Loafers Shoe',
            'Ankle Sneakers','Corporate Sneakers',
            'Ankle Canvas','Cut Canvas',
            'Canvas']

types = {'Ankle Shoe':['Skin','Suede'],
          'Corporate shoe':['Skin','Suede'],
          'Half Shoe':['Skin','Suede'],
         'Loafers Shoe':[],
          'Ankle Sneakers':[],
          'Corporate Sneakers':[],
           'Ankle Canvas':[],
          'Cut Canvas':[],
           'Canvas':[]
         }

brands = {'Ankle Shoe':['Clarks','Louise Viddon','Wine Dove','Terra Impossa',
                        'Next','Billionaire','Life Light','R6SI','Philip Plain',
                       'Goco','OMDE','Gucci','GSGS','Prada','Boricia','AB & CD',
                        "Verocuoio",'Alba','Timber Land','John Foster',
                       
                       ],
          'Corporate shoe':['Gucci','Santani','J Benato','GiorGio Armani','Roscote',
                            'Aldo','MJ','John Foster','Reaction (Kenneth Cole',
                            'Salvatore','Rossi','Ferragamo','Robert Wathe','Lioous MJ',
                            'Clarteed','Goco','Bayek','Clarks','Comotek','GP Gasper',
                            'Dsbant','Baxilium','Bata','Billionaire','Event','Addeheng',
                            'Chrome Beat','Ykadeng','Blilai','Diersten','Berluti','Sebago Duckside',
                            'Renato Dulbecc','Lious Vuitton','LV','Wine Dove','Hermes','Boricia',
                            'Dior','Versace','DNL','TK','J.M Weston','Prada','Roukie Dutti',
                            'Earnest','Tom Ford','Anax','Marc','Cavalli','Bunker','Sagreottino',
                            'Timber Land',''
                           ],
          'Half Shoe':['Feragamo','Anax','Tomford','Lious Vuitton','Fendi','Dior','Fashion',
                        
                      ],
          'Loafers Shoe':['Lious Vuitton','Cervo','Pedro','Clarteed','Ferragamo',
                          'Gucci','Giorgio Armani','Timber Land', 'Versace',
                          'Clarks','Hermes','Tods','Le Sunda',
                         
                         ],
          'Ankle Sneakers':['Dabant','AB & CD','Vinsor','Amashi','Lieut Vinson','Mr Franck',
                            'Mirko Gicoioli','Lauise Viddon','S.T','Roscote','Boss Victor',
                            'L.V','Marc Cavalli','Philip Plein','Gucci',
                           ],
          'Corporate Sneakers':['Sunda','Balenciaga','Unity Human','SNRD','Fashion','Chasse',
                                'Prada','L.V','Philip Plein','Zegna','Dolce & Gabbana','Philip',
                                'Plein','S.T','Louis Vuitton','Botega Veneta','Y-3'
                               
                               ],
           'Ankle Canvas':[],
          'Cut Canvas':[],
           'Canvas':['M11','Sport','Inextenso','Denchen','L. Bite','Fashion','Nike','Le Coq Sportif']
         }

In [4]:
data = []
for cat in category:
    temp = []
    for type_ in types[cat]:
        for brand in brands[cat]:
            for color in colors:
                for size in sizes:
                    temp = [product,cat,brand,type_,
                                            color,size]
                    data.append(temp)

shoes = pd.DataFrame(data,columns=cols)

In [10]:
shoes[(shoes['Category'] == 'Ankle Shoe') & (shoes['Brand'] == 'Clarks')  ]

    Product    Category   Brand   Type  Color  Size
0     Shoes  Ankle Shoe  Clarks   Skin  Black    36
1     Shoes  Ankle Shoe  Clarks   Skin  Black    38
2     Shoes  Ankle Shoe  Clarks   Skin  Black    40
3     Shoes  Ankle Shoe  Clarks   Skin  Black    42
4     Shoes  Ankle Shoe  Clarks   Skin  Black    44
..      ...         ...     ...    ...    ...   ...
667   Shoes  Ankle Shoe  Clarks  Suede  Brown    58
668   Shoes  Ankle Shoe  Clarks  Suede  Brown    60
669   Shoes  Ankle Shoe  Clarks  Suede  Brown    62
670   Shoes  Ankle Shoe  Clarks  Suede  Brown    64
671   Shoes  Ankle Shoe  Clarks  Suede  Brown    66

[64 rows x 6 columns]

In [6]:
product = "Pam"
cols = ['Product','Category','Brand','Type','Color','Size',
       ]
category = ['Skin']

types = {'Skin':['Normal',"Stock"]
         }

brands = {
          'Stock':['Louis Vuitton','Fendi','Fashion','Dior','Gucci',
                   'DS Quared','Hermes','Versace','Valentino','Suicoke',
                   'Lacoste','Emperor Armini','Philip Plein','Ferragmo',
                   'Salvatore','Chloe','BurBerry'
                  ]
         }

In [7]:
product = "Sandals"
cols = ['Product','Category','Brand','Type','Color','Size',
       ]
category = ['Skin']

types = {'Skin':['Normal',"Stock"],
         }

brands = {
          'Stock':['Versace','Emperor Armini'
                  ]
         }

In [8]:
product = "Slippers"
cols = ['Product','Category','Brand','Type','Color','Size',
       ]
category = ['Dunlop','Rubber']

types = {'Dunlop':['Normal',"Stock"],
         'Rubber':['Normal',"Stock"],
         }

brands = {
          'Stock':['Versace','Emperor Armini'
                  ]
         }